import type { MetadataRoute } from 'next';

/**
 * Web app manifest, served at /manifest.webmanifest. Icons are generated by
 * scripts/generate-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: '/',
    name: 'CARE Workflow',
    short_name: 'CARE Workflow',
    description:
      'Know who holds every task now, who handled it before, and how long each step took.',
    start_url: '/dashboard',
    scope: '/',
    display: 'standalone',
    orientation: 'any',
    // Matches the light canvas, so the splash screen does not flash on launch.
    background_color: '#F8F7F5',
    theme_color: '#F8F7F5',
    categories: ['productivity', 'business'],
    prefer_related_applications: false,
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
    // Offered on a long-press of the home-screen icon or a right-click in the taskbar.
    shortcuts: [
      { name: 'New task', url: '/tasks/new', description: 'Start a new task' },
      { name: 'My tasks', url: '/tasks', description: 'Every task you can see' },
      { name: 'Approvals', url: '/approvals', description: 'Decisions waiting on you' },
    ],
  };
}
